### ISSUE TITLE
Where can I get the sourcecode for the iOS App?

### ISSUE THREAD

**Issue by 343max** [owncloud/ios-legacy#54]

**Comment by jancborchardt** [comment]
So now that the code and process is open source since some time, it would be cool to see some contributions from you folks :) @343max @dbeuchler @tillmzw @oehokie @kuriakinzeng @uvesten @hfye @steve0hh @thomersch @oktawave-code @k3a @decorhouse @wjacker2 @dsalunga @Kronusdark @jairoserrano @supportreq @icecreammatt @FezVrasta @ladrua @SOFRACS @angelovAlex – is anything preventing you from that so far? If so, please open issues about that: https://github.com/owncloud/ios/issues

You’re also very welcome in our IRC channel **#owncloud-ios** (freenode IRC) :)

**Comment by ladrua** [comment]
Hello,
What is preventing me, is the license. Since I can't release it in App Store under my own brand. So I'm forced to work on my own version of an ios app. I really like owncloud, and it's community, but I need to supply my users with a branded app, and that takes up most of my Objective-C time at the moment. 
I know I can buy a license with ownCloud Inc. But that is to expensive for us at the moment. 


Regards
Stian

**Comment by jancborchardt** [comment]
As far as I understand, branding is fine – but you have to distribute it by a different means than the appstore (thanks to Apple).

No one prevents you from contributing to the repository though, working on features & fixes. :)

**Comment by ladrua** [comment]
I think there then also is a limit of 100 clients, and we want it through the App store. 
And yes, when I am finished with everything I have to do for my clients, there is nothing preventing me from contributing. But my backlog is quite big. Hopefully we will get more people working at our company, and we will of course share back to the ownCloud community. That is very important for us, and the type of company we want to be. 

As a try to help, I opensourced our webdav ios app, under MIT license... With that license people can rebrand and launch in the App store. So we are contributing in the ways we can. Wish we could do more, but we will in time.
